version: 2.1
orbs:
  slack: circleci/slack@4.12.5

commands:
  notify_slack_error:
    steps:
      - slack/notify:
          event: fail
          template: basic_fail_1

  notify_slack_pass:
    steps:
      - slack/notify:
          event: pass
          template: basic_success_1

jobs:
  build:
    working_directory: ~/project
    docker:
      - image: cimg/openjdk:20.0.1

    steps:
      - checkout
      - run: mvn clean
      - run: mvn test
      - run: mvn install

